### PR TITLE
Use JSON for reading/writing recipes file

### PR DESCRIPTION
**Pull request by derekphilipau**
This change uses the jsonpickle library (https://jsonpickle.github.io/) to automatically serialize and deserialize recipe objects in Lipgloss to a recipe file, JSONRecipeShelf.json

I've added an extra recipe in addition to the Default Recipe Bounds, Recipe Bounds 1.  This was just for testing and can be deleted.

I'm not sure if you want to go with using JSON or not.  I just wanted to try learning a bit of Python and use github more :)

### CODE REVIEW

**Comment by PieterMostert** [comment]
I tried it out locally, and it seemed to work. But after trying to delete the additional recipes (I added another one while I was testing), I'm stuck with Github telling me the JSONRecipeShelf.json file is conflicted, and I can't figure out what the problem is, or revert to your original pull request. I'll have to try again tomorrow.

**Comment by derekphilipau** [comment]
I removed the test recipe from the data file, now only Default Recipe Bounds is included.  Please let me know if you have any problems.

Is there a case where a user would want to change the Default Recipe Bounds?  If not, I think these bounds (the first entry in the recipe file) could moved into a separate file (e.g. JSONDefaultBounds.json).  This would prevent users from accidentally hitting "Save" and overwriting these defaults.  

Also, I think it's a good idea to isolate all data files (both the Shelves and JSON) in a separate directory.  If you think using JSON is a good way to go, then I can start converting all the other Shelf dat files to use JSON instead.

**Comment by PieterMostert** [comment]
I don't have time to check it out now, but I'm sure your changes are fine. I have no objection to using JSON instead of shelve. I've realised since yesterday that I could just have edited the JSONRecipeShelf.json file to delete the second recipe, which is much simpler than what I used to do. The only downside I can see is that users need to instal the jsonpickle module.

Just one comment: I see you've simplified the way the program assigns the index. This works as long as users don't delete objects (so for recipes at the moment, this isn't a problem). But if the list of indices is ['0', '1', '2'] and you delete the object indexed by '1', the next time you add an object, you'll over-ride the pre-existing object indexed by '2'.

Even if users don't want to change the default limits, they'll probably want to change the default materials, once they've added their own. I'm thinking of modifying the options in the File menu when the default recipe is open to 'Save new recipe bounds' and 'Save default recipe bounds'. There may be a better way of doing this.

Isolating data file sounds like a good idea.

**Comment by derekphilipau** [comment]
If we modify Lipgloss to use JSON, it will be easier later to implement an API service that web applications can use.  And as Tom pointed out, versioning in git will be simpler.  jsonpickle allows for JSON serializing of arbitrary python objects, but I will try again using a serializer class that will standardize the JSON without needing jsonpickle.  Aside from handling recipe deletions, we'll need to move the RecipeShelf code out of the recipe class.  I'll update this commit as soon as I can.

**Comment by PieterMostert** [comment]
Don't go out of your way to avoid jsonpickle. Anyone who can install PuLP should be able to install jsonpickle.

**Comment by derekphilipau** [comment]
OK, I've made a number of changes:
* Moved JSON data files (i.e. JSONRecipeShelf.json) into "data" directory
* Custom JSON serializer located in "serializers" directory.  No dependency on jsonpickle.  Rather than relying on an existing library like jsonpickle to automatically serialize/deserialize an object (e.g. Recipe), we should make our own JSON interface not dependent upon the object implementation.
* Fixed ID issue you mentioned when adding a new recipe.  get_highest_recipe_key() is used to get the highest key in the recipe dict 
* Changed "File->Open" option to "File->Recipes" and added a delete button for each recipe.  Default recipe cannot be deleted.  Deleting the current recipe switches the user to the default recipe.

Finally, I removed the cached python files from the repository and updated .gitignore to ignore these files.

**Comment by derekphilipau** [comment]
Final change!  I wasn't properly closing the file handles when writing JSON.  Also, I moved the initialization of the Default Recipe to GUI.py (line 27).  recipes.py shouldn't need to concern itself with writing to the data file.  (_Define default recipe, in the case where class definitions have changed, or when things have just generally gotten messy_)  However, the Recipe class is still responsible for knowing how to create a default recipe (function get_default_recipe())  I hope you agree with this change.

**Comment by derekphilipau** [comment]
I'm firing the kiln today and learning python.  Added the ability to name a new recipe when saving.  If a name is not entered, the default is used, e.g. "Recipe Bounds X".

**Comment by PieterMostert** [comment]
Thanks for doing this! The changes all seem to work. 

When saving a new recipe, I would have replaced the Label widget that recipe_name is assigned to with an Entry widget, so users can enter the name without having a window pop up, and also change the name later. 

I'm getting a conflict with recipes.cpython-36.cpy in _pycache_, so can't merge your pull request. Any idea how to resolve this?

**Comment by derekphilipau** [comment]
I'm learning as I go, I hope I don't a) add anything out of line with your vision and b) mess up the git repository.

I _thought_ I had completely deleted __pycache__ and all .pyc files within it from git?  You might have to try `git rm -f *.pyc` then `git rm __pycache__/` and get rid of those files in your branch as well?

As for the recipe name save, I thought of doing it the way you suggest but could not figure out how to add an Entry as a menu item.  If there is a way to do this I think we should!

**Comment by PieterMostert** [comment]
I think the problem is more likely to be that I'm not using git properly. I've been trying to do things with the Github GUI, but I really need to learn how to use the command line. I think I've managed to merge your changes with the master branch on my local repo.

**Comment by PieterMostert** [comment]
Looks like that worked, although it seems the _pycache_ folder is regenerated automatically.

The only real change I made is to delete the RecipeShelf files, since we aren't using the shelve module to handle the recipes anymore.

**Comment by derekphilipau** [comment]
The problem is that both of us are probably not using git properly!  Yeah, my changes are working but _pycache_ and the cache files are still in the repo.  Now that the _.gitignore_ is updated to ignore those files, I think if you tried removing them with git again and pushing the commit they should be gone for good?  I also thought I had deleted those RecipeShelf files, I guess they reappeared as well :)  I'm not sure how much free time I will have now that the firing is over, but if you think it's a good idea I'd like to continue converting the Shelves to JSON?

**Comment by PieterMostert** [comment]
OK, I did what you suggested with _pycache_, and it seems to be working. I'm happy for you to carry on converting the Shelves to JSON. I'll see if I can get the way recipes are named to work the way I described.

**Pull request merged**
